---
name: Add issues to project

description: |
  This action adds issues to a project if they are not already in the project.

inputs:
  projectId:
    description: "Project ID"
    required: true
  issueNumber:
    description: "Issue Number"
    required: true
  githubToken:
    description: "GH token with project write access"
    required: true

runs:
  using: "composite"
  steps:
    - id: get_project_count
      uses: octokit/graphql-action@v2.3.2
      with:
        # API https://docs.github.com/en/graphql/reference/objects#issue
        query: |
          query getProjectCount($owner:String!, $repo:String!, $issue: Int!) {
            repository(name: $repo, owner: $owner) {
              issue: issue(number: $issue) {
                projectsV2 {
                  totalCount
                }
              }
            }
          }
        variables: |
          owner: "camunda"
          repo: "camunda"
          issue: ${{ inputs.issueNumber }}
      env:
        GITHUB_TOKEN: ${{ inputs.githubToken }}

    - id: has-project
      shell: bash
      run: echo "result=${{ fromJSON(steps.get_project_count.outputs.data).repository.issue.projectsV2.totalCount > 0 }}" >> $GITHUB_OUTPUT

    - id: add-to-project
      name: Add to project
      uses: actions/add-to-project@v1.0.2
      if: ${{ steps.has-project.outputs.result == 'false' }}
      with:
        project-url: https://github.com/orgs/camunda/projects/${{ inputs.projectId }}
        github-token: ${{ inputs.githubToken }}
