---
name: Preview Environment Build

on:
  pull_request:
    types: [ labeled,synchronize ]

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}

defaults:
  run:
    # use bash shell by default to ensure pipefail behavior is the default
    # see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    shell: bash

jobs:
  build-operare:
    if: github.event.pull_request.state != 'closed' && (contains( github.event.label.name, 'deploy-preview') || contains( github.event.pull_request.labels.*.name, 'deploy-preview'))
    name: Operate Build
    uses: ./.github/workflows/operate-ci-build-reusable.yml
    secrets: inherit
    with:
      branch: ${{ github.head_ref }}
      previewEnv: true
      commitSha: ${{ github.sha }}

  build-tasklist:
    if: github.event.pull_request.state != 'closed' && (contains( github.event.label.name, 'deploy-preview') || contains( github.event.pull_request.labels.*.name, 'deploy-preview'))
    name: Tasklist Build
    uses: ./.github/workflows/tasklist-ci-build-reusable.yml
    secrets: inherit
    with:
      branch: ${{ github.head_ref }}
      previewEnv: true
      commitSha: ${{ github.sha }}

  build-zeebe:
    if: github.event.pull_request.state != 'closed' && (contains( github.event.label.name, 'deploy-preview') || contains( github.event.pull_request.labels.*.name, 'deploy-preview'))
    name: Zeebe Build
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-docker-snapshot
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-zeebe
        with:
          secret_vault_secretId: ${{ secrets.VAULT_SECRET_ID }}
          secret_vault_address: ${{ secrets.VAULT_ADDR }}
          secret_vault_roleId: ${{ secrets.VAULT_ROLE_ID }}

      - uses: ./.github/actions/build-zeebe
        id: build-zeebe
        with:
          maven-extra-args: -T1C -PskipFrontendBuild

      - uses: ./.github/actions/build-platform-docker
        id: build-zeebe-docker
        with:
          repository: registry.camunda.cloud/team-camunda/zeebe
          version: pr-${{ github.sha }}
          platforms: ${{ env.DOCKER_PLATFORMS }}
          push: true
          distball: ${{ steps.build-zeebe.outputs.distball }}
          secret_vault_secretId: ${{ secrets.VAULT_SECRET_ID }}
          secret_vault_address: ${{ secrets.VAULT_ADDR }}
          secret_vault_roleId: ${{ secrets.VAULT_ROLE_ID }}
          preview-env: true
